# Generated by Django 3.2.4 on 2021-07-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacategory',
            name='identifier',
            field=models.CharField(default='a', max_length=16, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datacategory',
            name='name',
            field=models.CharField(default='s', max_length=32),
            preserve_default=False,
        ),
    ]
